---
title: "Obtain an access to the Reporting API"
#author: "Artem Klevtsov"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Reporting API}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
```
 
To access the Reporting API Google Analytics `RGA` package provides the following functions:

* `get_ga` - returns Analytics data for a view (profile);
* `get_mcf` - returns Analytics Multi-Channel Funnels data for a view (profile);
* `get_rt` - returns real time data for a view (profile).

All of this functions return a data frame including the data for a view (profile).

The following parameters are available for queries to the API reports:

* `profile.id` - profile (view) ID. Can be obtained using the `list_profiles` or via the web interface Google Analytics;
* `start.date` - the start date for collecting data formatted as YYYY-MM-DD. Also values such as "today", "yesterday", "ndaysAgo" are allowed, where n is the number of days;
* `end.date` - the end date for collecting data formatted as YYYY-MM-DD. Also values such as "today", "yesterday", "ndaysAgo" are allowed, where n is the number of days;
* `metrics` -  comma-separated list of values ​​of metrics (metrics), for example, `"ga:sessions,ga:bounces"`. The number of metrics cannot exceed 10 indicators for a single request;
* `dimensions` - comma-separated list of values ​​of measurements (dimensions), for example, `"ga:browser,ga:city"`. The number of dimensions cannot exceed 7 measurements at a single request;
* `sort` - comma-separated list of metrics (metrics) and measurements (dimensions) which determine the order and direction of sorting data. The reverse sort order is defined by “-“ before the relevant metric;
* `filters` - comma-separated list of metric (metrics) and measurement (dimensions) filters that are imposed when data is selected;
* `segment` - segments that are used when retrieving data. Can be obtained using the `list_segments` or via the web interface Google Analytics;
* `sampling.level` - the desired sampling level. Allowed values: "default", "faster", "higher_precision";
* `start.index` - index of the first returned result (line number);
* `max.results` - maximum number of fields (rows) of the returned results;
* `token` - object of class `Token2.0` which contains data with a valid authorization data. Can be obtained using the `authorize` function;
* `messages` - logical argument which includes displaying of additional messages during the data request.

The following arguments: `profile.id`, `start.date`, `end.date` and `metrics` are required for `get_ga` and `get_mcf` (`get_rt` requires only `profile.id` and `metrics`). Notice that all arguments must be character strings of unit length. The exception is `profile.id` which can be both character string and numeric.

This is an example of data obtaining for the last 30 days:

```r
ga_data <- get_ga(profile.id = XXXXXXXX, start.date = "30daysAgo", end.date = "yesterday",
                  metrics = "ga:users,ga:sessions,ga:pageviews")
```

Sometimes it is necessary to obtain the data for the entire monitoring period through service Google Analytics. For these purposes the package `RGA` provides the function `get_firstdate` which takes a charming profile ID (submission) as an argument:

```r
first_date <- get_firstdate(profile.id = XXXXXXXX)
```

Now we can use the variable `first_date` as the argument `start.date` when we call the `get_ga` function:

```r
ga_data <- get_ga(profile.id = XXXXXXXX, start.date = first_date, end.date = "yesterday",
                  metrics = "ga:users,ga:sessions,ga:pageviews")
```

## Sampled data

If at least one of the following thresholds is met Analytics samples data accordingly:

* 1,000,000 maximum unique dimension combinations for any type of query;
* 500,000 maximum sessions for special queries where the data is not already stored.

In order to avoid this, you can split the query into multiple small queries (day-by-day). You can get this day-by-day data by using the following code:

```r
dates <- seq(as.Date("2012-01-01"), as.Date("2012-02-01"), by = "days")
ga_data <- aggregate(. ~ keyword, FUN = sum,
                     data = do.call(rbind, lapply(dates, function(d) {
                       get_ga(profile.id = XXXXXXXX, start.date = d, end.date = d,
                       metrics = "ga:sessions", dimensions = "ga:keyword",
                       filter = "ga:medium==organic;ga:keyword!=(not provided);ga:keyword!=(not set)")})))
```

Note: a formula in `aggregate` function should include all Google Analyitcs dimensions without prefix ("ga:" or "mcf:").

## References

- [Core Reporting API - Dimensions & Metrics Reference](https://developers.google.com/analytics/devguides/reporting/core/dimsmets);
- [Multi-Channel Funnels Reporting API - Dimensions & Metrics Reference](https://developers.google.com/analytics/devguides/reporting/mcf/dimsmets/)
- [Real Time Reporting API - Dimensions & Metrics Reference](https://developers.google.com/analytics/devguides/reporting/realtime/dimsmets/)
- [Core Reporting API - Common Queries](https://developers.google.com/analytics/devguides/reporting/core/v3/common-queries);
- [Google Analytics Demos & Tools - Query Explorer](https://ga-dev-tools.appspot.com/explorer/);
